<a href="https://colab.research.google.com/github/SakshamRimal/Deep-Learning/blob/main/04_ANN/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
df = pd.read_csv("/content/drive/MyDrive/Deep Learning/04_ANN/Churn_Modelling.csv")

In [11]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)



TensorFlow version: 2.18.0


In [12]:
# import some basic library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [14]:
# classification model nai ho yo ni
df.shape

(10000, 14)

In [15]:
# divide the dataset into independent and dependent features
X = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [16]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [17]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [18]:
geography = pd.get_dummies(X['Geography'], drop_first=True).astype(int)
gender = pd.get_dummies(X['Gender'], drop_first=True).astype(int)

In [19]:
# concatenate these variables into dataframes
# first drop these
X.drop(['Geography', 'Gender'], axis=1, inplace=True)

In [20]:
X = pd.concat([X, geography, gender], axis=1)

In [21]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [22]:
# splitting the dataset into train test split
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2 , random_state=0)

In [23]:
# feature scaling is  also required in ANN
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [25]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [26]:
X_train.shape

(8000, 11)

Tensorflow => Google
Pytorch => Facebook
Keras => Wrapper
So, tensorflow and keras got integrated

In [27]:
## now create the ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU, PReLU, ELU, ReLU
from tensorflow.keras.layers import Dropout

In [30]:
# lets initialize the ANN
classifier = Sequential()
# sequential is used for making the layers imagine as a block where there is neural netwrok

In [31]:
# adding the input layer
# now dense is used to connect the neurons in our dataset we have 11 training data so unit is equal to 11
classifier.add(Dense(units=11 , activation='relu'))

In [32]:
# adding the first hidden layer
classifier.add(Dense(units=6 , activation='relu'))
classifier.add(Dropout(0.3))

In [33]:
# adding the second hidden layer
classifier.add(Dense(units=6 ,activation='relu'))

In [49]:
# adding the output layer
classifier.add(Dense(1,activation='sigmoid'))
# now our neural network is read

In [50]:
import tensorflow as tf
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [51]:
classifier.compile(optimizer=opt , loss='binary_crossentropy' , metrics=['accuracy'])

In [59]:
## Early Stopping makes sures that if the accuracy is all not increasing then we stop training the model
# import the paramets of earlystopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(
    monitor='val_loss',
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode='auto',
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0
)


In [60]:
model_history = classifier.fit(X_train , y_train , validation_split=0.33 , batch_size=10 , epochs=1000 , callbacks=early_stopping)

Epoch 1/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8747 - loss: 0.3185 - val_accuracy: 0.8512 - val_loss: 0.3837
Epoch 2/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8644 - loss: 0.3134 - val_accuracy: 0.8542 - val_loss: 0.3729
Epoch 3/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8738 - loss: 0.3137 - val_accuracy: 0.8535 - val_loss: 0.3765
Epoch 4/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8702 - loss: 0.3187 - val_accuracy: 0.8519 - val_loss: 0.3739
Epoch 5/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8679 - loss: 0.3246 - val_accuracy: 0.8459 - val_loss: 0.3794
Epoch 6/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8616 - loss: 0.3208 - val_accuracy: 0.8508 - val_loss: 0.3744
Epoch 7/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8715 - loss: 0.3226 - val_accuracy: 0.8504 - val_loss: 0.3798
Epoch 8/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8697 - loss: 0.3165 - 

In [61]:
# For epoch = 41 the training has stopped

In [63]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [64]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred >= 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step


In [66]:
## make the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[1544,   51],
       [ 226,  179]])

In [68]:
# alculate the accuracy
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred , y_test)
score

0.8615

In [69]:
# get the information of weights
classifier.get_weights()

[array([[-1.23013091e+00,  5.00693798e-01,  1.93631753e-01,
         -6.95297539e-01,  7.42420733e-01,  5.05748212e-01,
          9.07646343e-02,  1.55917978e+00,  5.70553243e-01,
          2.60471702e+00, -1.40391096e-01],
        [-3.34313011e+00, -1.65022254e+00, -1.01808858e+00,
         -2.52527547e+00, -7.21947908e+00,  2.70434380e+00,
         -2.18896079e+00, -6.15527773e+00,  4.22284079e+00,
         -1.81297243e+00, -4.00072902e-01],
        [-1.81114733e+00,  1.16591133e-01,  6.11946702e-01,
          2.27759910e+00, -1.34264514e-01,  7.23866105e-01,
         -1.59467983e+00,  1.15681565e+00, -7.85601556e-01,
          2.03251386e+00, -2.28868008e-01],
        [-2.45679593e+00, -4.58744907e+00, -4.94582319e+00,
          4.40583304e-02, -1.73899436e+00, -1.10969448e+00,
         -1.51834905e+00,  2.79030538e+00,  9.53175351e-02,
          6.23744845e-01,  1.45361710e+00],
        [-1.65092564e+00,  4.14845371e+00, -2.76199555e+00,
          2.70105290e+00,  1.02375150e+00, -